### PR TITLE
[ML-404] Solved the GPU acquisition bug and improve the acquisition algorithm training time.

### LINKED ISSUE #404: After integrating DAOS, the oneccl ZE_AFFINITY_MASK parameter does not work, resulting in all GPUs being obtained when getting_gpus()

### PR DESCRIPTION
**Pull request by minmingzhu**
## What changes were proposed in this pull request?

closes #404

### CODE REVIEW

File: mllib-dal/src/main/native/OneCCL.cpp [hunk 1]
```diff
@@ -73,33 +76,47 @@ JNIEXPORT jint JNICALL Java_com_intel_oap_mllib_OneCCL_00024_c_1init(
...
         comm_size = getComm().size();
         break;
     }
 #ifdef CPU_GPU_PROFILE
     case ComputeDevice::gpu: {
-        auto gpus = get_gpus();
-        sycl::queue queue{gpus[0]};
+        auto gpus_count = gpus.size();
+
+        logger::println(logger::INFO, "OneCCL (native): gpus_count %d",
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/OneCCL.cpp:91]:
```suggestion
        logger::println(logger::INFO, "OneCCL (native): gpu number is %d",
```

File: mllib-dal/src/main/native/OneCCL.cpp [hunk 2]
```diff
@@ -73,33 +76,47 @@ JNIEXPORT jint JNICALL Java_com_intel_oap_mllib_OneCCL_00024_c_1init(
...
+                        gpus_count);
+        sycl::device selected_device;
+        if (gpus_count == 1) {
+            selected_device = gpus[0];
+        } else if (gpus_count == 12) {
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/OneCCL.cpp:96]: You can't assume 12 gpus right?

File: mllib-dal/src/main/native/PCAImpl.cpp [hunk 3]
```diff
@@ -195,30 +189,27 @@ static void doPCAOneAPICompute(
...
-            std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1)
-                .count();
-        logger::println(logger::INFO, "PCA (native): Eigen step took %d secs",
-                        duration / 1000);
+        logger::println(logger::INFO, "Eigenvectors:");
+        printHomegenTable(result_train.get_eigenvectors());
+        logger::println(logger::INFO, "Eigenvalues:");
+        printHomegenTable(result_train.get_eigenvalues());
+
+        auto t2 = std::chrono::high_resolution_clock::now();
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/PCAImpl.cpp:209]: don't count print into the timing?

File: mllib-dal/src/main/native/service.h [hunk 4]
```diff
@@ -89,18 +89,33 @@ inline void printHomegenTable(const oneapi::dal::table &table) {
...
             logger::println(logger::NONE, "");
         }
+
     } else {
         for (std::int64_t i = 0; i < 5; i++) {
             logger::print(logger::INFO, "");
-            for (std::int64_t j = 0; j < table.get_column_count(); j++) {
-                logger::print(logger::NONE, "%10f",
-                              x[i * table.get_column_count() + j]);
+            if (table.get_column_count() <= 20) {
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/service.h:109]: column_count = table.get_column_count();
column_count = column_count <20 ? count : 20;
Then use column_count for the loop

File: mllib-dal/src/main/native/SummarizerImpl.cpp [hunk 5]
```diff
@@ -213,9 +210,23 @@ static void doSummarizerOneAPICompute(
...
+        HomogenTablePtr maxTable =
+            std::make_shared<homogen_table>(result_train.get_max());
+        HomogenTablePtr minTable =
+            std::make_shared<homogen_table>(result_train.get_min());
+        auto t2 = std::chrono::high_resolution_clock::now();
+        float duration = std::chrono::duration<float>(t2 - t1).count();
+        logger::println(logger::INFO,
+                        "Summarizer (native): training step took %f secs",
+                        duration);
         logger::println(logger::INFO, "Minimum");
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/SummarizerImpl.cpp:230]:
```suggestion
        logger::println(logger::INFO, "Minimum:");
```

same for others

File: mllib-dal/src/main/native/LinearRegressionImpl.cpp [hunk 6]
```diff
@@ -237,12 +237,19 @@ static jlong doLROneAPICompute(
...
     linear_regression_gpu::train_result result_train =
         preview::train(comm, linear_regression_desc, xtrain, ytrain);
     if (isRoot) {
         HomogenTablePtr result_matrix = std::make_shared<homogen_table>(
             result_train.get_model().get_betas());
+        auto t2 = std::chrono::high_resolution_clock::now();
+        float duration = std::chrono::duration<float>(t2 - t1).count();
+        logger::println(
+            logger::INFO,
+            "Linear regression (native): training step took %f secs.",
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/LinearRegressionImpl.cpp:251]:
```suggestion
            "LinearRegression (native): training step took %f secs.",
```

File: mllib-dal/src/main/native/NaiveBayesDALImpl.cpp [hunk 7]
```diff
@@ -159,9 +159,8 @@ Java_com_intel_oap_mllib_classification_NaiveBayesDALImpl_cNaiveBayesDALCompute(
     logger::println(logger::INFO, "OneDAL (native): training model finished");
 
     auto t2 = std::chrono::high_resolution_clock::now();
-    auto duration =
-        std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();
-    logger::println(logger::INFO, "training took %d secs", duration / 1000);
+    float duration = std::chrono::duration<float>(t2 - t1).count();
+    logger::println(logger::INFO, "training took %f secs", duration);
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/NaiveBayesDALImpl.cpp:163]:
```suggestion
    logger::println(logger::INFO, "NaiveBayes (native): training took %f secs", duration);
```

File: mllib-dal/src/main/native/SummarizerImpl.cpp [hunk 8]
```diff
@@ -54,11 +54,10 @@ static void doSummarizerDAALCompute(JNIEnv *env, jobject obj, size_t rankId,
     localAlgorithm.compute();
 
     auto t2 = std::chrono::high_resolution_clock::now();
-    auto duration =
-        std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();
+    float duration = std::chrono::duration<float>(t2 - t1).count();
     logger::println(logger::INFO,
-                    "low_order_moments (native): local step took %d secs",
-                    duration / 1000);
+                    "low_order_moments (native): local step took %f secs",
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/SummarizerImpl.cpp:59]:
```suggestion
                    "Summarizer (native): local step took %f secs",
```

File: mllib-dal/src/main/native/SummarizerImpl.cpp [hunk 9]
```diff
@@ -82,11 +81,10 @@ static void doSummarizerDAALCompute(JNIEnv *env, jobject obj, size_t rankId,
         .wait();
     t2 = std::chrono::high_resolution_clock::now();
 
-    duration =
-        std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();
+    duration = std::chrono::duration<float>(t2 - t1).count();
     logger::println(logger::INFO,
-                    "low_order_moments (native): ccl_gather took %d secs",
-                    duration / 1000);
+                    "low_order_moments (native): ccl_gather took %f secs",
```
Comment (xwu-intel) [inline mllib-dal/src/main/native/SummarizerImpl.cpp:86]:
```suggestion
                    "Summarizer (native): ccl_gather took %f secs",
```

**Review by xwu-intel — APPROVED** [review]

**Review by xwu99 — APPROVED** [review]
